### ISSUE TITLE
Please support the stable release channel

### ISSUE THREAD

**Issue by marvinpan8** [sfu-db/connector-x#253]
When I compile with connectorx 0.2.3 rustc 1.58.1 (db9d1b20b 2022-01-20), but build the error.  Please support the stable release channel
```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> D:\cargo-cache\registry\src\192.168.14.111-407bed59a830ad4f\connectorx-0.2.3\src\lib.rs:1:1
  |
1 | #![feature(generic_associated_types)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by wangxiaoying** [comment]
Hi @marvinpan8 , thanks for bringing this up! As the error shows our code relies on the GAT feature in nightly. But it seems like the stabilization is very soon according to this [tracking issue](https://github.com/rust-lang/rust/issues/44265).
